# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AreaMonster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AreaMonster
  
  pod 'IQKeyboardManagerSwift'
  pod 'UBottomSheet'
  pod 'SkeletonView'
end
